# Generated by Django 4.1.1 on 2023-02-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crcikblogs', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
