# Generated by Django 4.1.1 on 2023-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcikblogs', '0010_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
