# Generated by Django 4.1.1 on 2023-02-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crcikblogs', '0015_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
