# Generated by Django 4.1.1 on 2023-02-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcikblogs', '0017_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
