# Generated by Django 4.1.1 on 2023-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcikblogs', '0018_alter_userdetails_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
