# Generated by Django 4.1.1 on 2023-02-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crcikblogs', '0020_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
