# Generated by Django 4.1.1 on 2023-02-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcikblogs', '0021_remove_post_cat_delete_category_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('userid', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('likes', models.IntegerField()),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post/')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
