# Generated by Django 4.1.1 on 2023-02-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcikblogs', '0022_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('userid', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('likes', models.IntegerField()),
                ('meme_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='post/')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
