# Generated by Django 4.1.1 on 2023-02-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcikblogs', '0024_alter_blog_date_alter_memes_date_alter_memes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='meme_likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meme_id', models.IntegerField()),
                ('userid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='post_likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('userid', models.CharField(max_length=30)),
            ],
        ),
    ]
